import React, { useCallback } from 'react';
import PageHeader from '../../components/control/PageHeader';
import { KpiStrip } from '../../components/control/Kpi';
import { Chip, StatusChip } from '../../components/control/Chips';
import { LoadingState, SectionCard, asArray, display, fmtTime } from '../../components/control/Common';
import { useControlData } from '../../hooks/useControlData';
import { controlPlaneApi } from '../../services/controlPlaneApi';
const number = (value) => new Intl.NumberFormat('en-IN').format(Number(value || 0));
const money = (value, currency = 'USD') => value == null ? 'Not available' : `${currency === 'USD' ? '$' : `${currency} `}${Number(value).toFixed(4)}`;
const isLlm = (event) => ['provider_reported', 'estimated'].includes(event.usage_source);

export default function UsageCost() {
  const fetchData = useCallback(async () => { const [summary, events, budgets] = await Promise.all([controlPlaneApi.getUsageSummary(), controlPlaneApi.listUsageEvents(), controlPlaneApi.getUsageBudgets()]); return { summary, events: asArray(events, 'events'), budgets }; }, []);
  const state = useControlData(fetchData, [], 10000); const summary = state.data?.summary; const events = state.data?.events || [];
  const budgets = state.data?.budgets || summary?.budgets || {};
  const llm = events.filter(isLlm); const nonLlm = events.filter((event) => !isLlm(event)); const latency = Object.values(summary?.average_latency_by_agent || {}); const avg = latency.length ? Math.round(latency.reduce((a, b) => a + Number(b || 0), 0) / latency.length) : 0;
  return <><PageHeader title="Usage & Cost" subtitle="Estimated usage telemetry for governance visibility." right={<button className="cc-button" onClick={state.reload}>Refresh</button>} /><LoadingState loading={state.loading} error={state.error} />
    {!state.loading && !state.error && <><KpiStrip items={[{ label: 'LLM Runs', value: number(llm.length), accent: 'blue' }, { label: 'Non-LLM Runs', value: number(nonLlm.length), accent: 'grey' }, { label: 'Token Usage', value: number(summary?.total_tokens), accent: 'teal' }, { label: 'Estimated Cost', value: llm.length ? money(summary?.estimated_total_cost, summary?.currency) : 'Not available', accent: 'purple' }, { label: 'Average Latency', value: `${avg} ms`, accent: 'blue' }]} />
    {!llm.length && <div className="cc-notice info cc-top-gap">No LLM token usage recorded yet. Run Policy Assistant or Loan Assessment to populate token and estimated cost telemetry.</div>}
    <BudgetPanel budgets={budgets} />
    <div className="cc-grid-2 cc-top-gap"><Metric title="Token Usage by Agent" values={summary?.tokens_by_agent} render={number} /><Metric title="Estimated Cost by Agent" values={llm.length ? summary?.cost_by_agent : {}} render={(v) => money(v, summary?.currency)} /></div>
    <UsageTable title="Latest LLM Usage Events" events={llm} empty="No LLM token usage recorded yet." /><UsageTable title="Non-LLM / Latency-only" events={nonLlm} empty="No non-LLM usage events recorded." />
    </>}
  </>;
}
function Metric({ title, values, render }) { const rows = Object.entries(values || {}); return <SectionCard title={title}>{!rows.length ? <div className="cc-empty">No model usage recorded.</div> : <div className="cc-metric-list">{rows.map(([name, value]) => <div className="cc-metric-row" key={name}><span>{name}</span><strong>{render(value)}</strong></div>)}</div>}</SectionCard>; }
function limitText(policy, key, render = number) { return policy?.[key] == null ? 'Not configured' : render(policy[key]); }
function BudgetPanel({ budgets }) {
  const definitions = budgets?.definitions || []; const periods = budgets?.periods || []; const events = budgets?.events || [];
  const byDefinition = Object.fromEntries(periods.map((p) => [p.definition_id, p]));
  return <SectionCard className="cc-top-gap" title="Runtime Budget Enforcement" subtitle="Configured policy, current period usage, remaining budget, and persisted warning/block events. Cost values are shown only when pricing exists.">
    {!definitions.length ? <div className="cc-empty">No model budget definitions have been activated by runtime usage yet.</div> : <div className="cc-table-scroll"><table className="cc-table"><thead><tr><th>Agent</th><th>Period</th><th>Mode</th><th>Configured Budget</th><th>Current Usage</th><th>Remaining</th><th>Fallback</th></tr></thead><tbody>{definitions.map((d) => { const p = byDefinition[d.definition_id] || {}; const policy = d.policy || {}; const remainingTokens = policy.max_total_tokens == null ? null : Number(policy.max_total_tokens) - Number(p.total_tokens_used || 0) - Number(p.total_tokens_reserved || 0); const remainingCost = policy.max_cost == null ? null : Number(policy.max_cost) - Number(p.cost_used || 0) - Number(p.cost_reserved || 0); return <tr key={d.definition_id}><td>{display(d.agent_id)}</td><td>{display(policy.period || p.period_type)}</td><td><Chip value={policy.enforcement_mode || 'monitor'} label={display(policy.enforcement_mode || 'monitor')} /></td><td>Total {limitText(policy, 'max_total_tokens')} tokens<br />Cost {limitText(policy, 'max_cost', (v) => money(v, d.currency))}</td><td>{number(p.total_tokens_used)} used / {number(p.total_tokens_reserved)} reserved<br />{money(p.cost_used, d.currency)} used / {money(p.cost_reserved, d.currency)} reserved</td><td>{remainingTokens == null ? 'Tokens not capped' : `${number(Math.max(0, remainingTokens))} tokens`}<br />{remainingCost == null ? 'Cost not capped' : money(Math.max(0, remainingCost), d.currency)}</td><td>{display(policy.fallback_action || 'none')}<br /><span className="cc-muted">{(policy.allowed_fallback_deployments || []).join(', ') || 'No deployments'}</span></td></tr>; })}</tbody></table></div>}
    <BudgetEvents events={events} />
  </SectionCard>;
}
function BudgetEvents({ events }) { return <div className="cc-top-gap">{!events.length ? <div className="cc-empty">No budget warnings or blocks recorded.</div> : <div className="cc-table-scroll"><table className="cc-table"><thead><tr><th>Time</th><th>Agent</th><th>Event</th><th>Severity</th><th>Message</th><th>Trace</th></tr></thead><tbody>{events.map((e) => <tr key={e.event_id}><td>{fmtTime(e.created_at)}</td><td>{display(e.agent_id)}</td><td>{display(e.event_type).replaceAll('_', ' ')}</td><td><StatusChip status={e.severity} /></td><td>{display(e.message)}</td><td className="mono">{display(e.trace_id)}</td></tr>)}</tbody></table></div>}</div>; }
function UsageTable({ title, events, empty }) { return <SectionCard className="cc-top-gap" title={title}>{!events.length ? <div className="cc-empty">{empty}</div> : <div className="cc-table-scroll"><table className="cc-table"><thead><tr><th>Time</th><th>Agent</th><th>Run Type</th><th>Model / Provider</th><th>Tokens</th><th>Estimated Cost</th><th>Latency</th><th>Usage Source</th><th>Status</th></tr></thead><tbody>{events.map((e) => <tr key={e.usage_id}><td>{fmtTime(e.created_at)}</td><td>{display(e.agent_name || e.agent_id)}</td><td>{isLlm(e) ? 'LLM' : e.provider === 'external' ? 'External' : 'Non-LLM'}</td><td>{e.model && e.model !== 'unknown' ? `${e.provider} / ${e.model}` : e.provider === 'external' ? 'External service' : 'Not available'}</td><td>{e.total_tokens == null ? 'Latency only' : number(e.total_tokens)}</td><td>{money(e.estimated_total_cost, e.currency)}</td><td>{e.latency_ms == null ? 'Not available' : `${e.latency_ms} ms`}</td><td><Chip value={e.usage_source} label={String(e.usage_source || 'unknown').replaceAll('_', ' ')} /></td><td><StatusChip status={e.status} /></td></tr>)}</tbody></table></div>}</SectionCard>; }
